config/routes.rb
Rails.application.routes.draw do

  post 'modify_info' => 'purchaser/modify#update'
  get 'modify_info' => 'purchaser/modify#index'
  namespace :seller do
  get 'deal/result',as: :result
  end

  namespace :seller do
  post 'deal/sendout',as: :sendout
  end

  namespace :seller do
  get 'order/index',as: :order
  end

  root 'purchaser/home#index'
  get 'login' => 'admin/session#new'
  get 'signup' => 'admin/users#new'
  post 'login' => 'admin/session#create'
  post 'logout' => 'admin/session#destroy'
  get 'seller' => 'seller/home#index'
  get 'admin' => 'admin/home#index'
  namespace :admin do
    resources :applcts
    resources :users
    get 'product' => 'product#index'
  end

  namespace :purchaser do
    resources :lists
    resources :carts
    resources :orders
  end

  namespace :seller do
    resources :products
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/applct.rb
class Admin::Applct < ActiveRecord::Base
  belongs_to :user
  validates :user_id, uniqueness:{value:true,message:"您已经申请过了，请耐心等待"}
end

app/models/admin/user.rb
class Admin::User < ActiveRecord::Base
  has_secure_password
  has_many :products ,class_name:"Seller::Product"
  has_one :applct
  has_many :orders, class_name:"Seller::Order"
  before_create :set_money

  def discribe
    if self.identity == 0
      "买家"
    elsif self.identity == 1
      "卖家"
    else
      "管理员"
    end
  end
  def set_money
    self.money = 10000
  end
end

app/models/purchaser.rb
module Purchaser
  def self.table_name_prefix
    'purchaser_'
  end
end

app/models/purchaser/cart.rb
class Purchaser::Cart < ActiveRecord::Base
  has_many :lists
  has_one :order

  def add_product(product_id)
    current_list = lists.find_by_product_id(product_id)
    if current_list
      current_list.quantity += 1
    else
      current_list = lists.build(:product_id => product_id)
    end
    current_list
  end

  def total_price
    lists.to_a.sum{|item| item.total_price}
  end
end

app/models/purchaser/list.rb
class Purchaser::List < ActiveRecord::Base
  belongs_to :cart
  belongs_to :order
  belongs_to :product ,class_name:"Seller::Product"
  def total_price
    product.price * quantity
  end
end

app/models/purchaser/order.rb
class Purchaser::Order < ActiveRecord::Base
  belongs_to :cart
  belongs_to :user,class_name:"Admin::User"
  has_many :lists

  def total_price
    lists.to_a.sum{|item| item.total_price}
  end
end

app/models/seller.rb
module Seller
  def self.table_name_prefix
    'seller_'
  end
end

app/models/seller/product.rb
class Seller::Product < ActiveRecord::Base
  belongs_to :user ,class_name:"Admin::User"
  has_many :lists
  # before_destroy :ensure_not_referenced_by_any_list
  mount_uploader :avatar, ProductAvatarUploader

  private
  def ensure_not_referenced_by_any_list
    if lists.empty?
      return true
    else
      errors.add(:base,'List present')
      return false
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  skip_before_action :check_admin,only: [:new,:create]
  before_action :set_admin_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @admin_users = Admin::User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @admin_user = Admin::User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @admin_user = Admin::User.new(admin_user_params)
    @admin_user.identity = 0;
    respond_to do |format|
      if @admin_user.save
        session[:user_id] = @admin_user.id
        session[:username] = @admin_user.username
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @admin_user }
      else
        format.html { render :new }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update
    respond_to do |format|
      if @admin_user.update(admin_user_params)
        format.html { redirect_to @admin_user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_user }
      else
        format.html { render :edit }
        format.json { render json: @admin_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @admin_user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_user
      @admin_user = Admin::User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_user_params
      params.require(:admin_user).permit(:username, :password, :password_confirmation)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :check_admin

  private
  def check_admin
    if !login_user || login_user.identity<2
      respond_to do |format|
        format.html { redirect_to login_path}
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def login_user
    if !session[:user_id].nil?
      Admin::User.find_by_id(session[:user_id])
    else
      nil
    end
  end

  private
  def current_cart
    Purchaser::Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Purchaser::Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/controllers/purchaser_controller.rb
class PurchaserController < ApplicationController
  before_action :check_login
  private
  def current_cart
    Purchaser::Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Purchaser::Cart.create
    session[:cart_id] = cart.id
    cart
  end
  def check_login
    if !login_user
      respond_to do |format|
        format.html { redirect_to root_path}
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/seller_controller.rb
class SellerController < ApplicationController
  before_action :check_seller

  private
  def check_seller
    if !login_user||login_user.identity<1
      respond_to do |format|
        format.html { redirect_to root_path}
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_user
    if !session[:user_id].nil?
      Admin::User.find_by_id(session[:user_id])
    else
      nil
    end
  end
  def login_admin
    if login_user && login_user.identity==2
      login_user
    else
      nil
    end
  end
  def current_cart
    Purchaser::Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    cart = Purchaser::Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/helpers/purchaser_helper.rb
module PurchaserHelper
end

app/helpers/seller/deal_helper.rb
module Seller::DealHelper
end

app/helpers/seller/home_helper.rb
module Seller::HomeHelper
end

app/helpers/seller/order_helper.rb
module Seller::OrderHelper
end

app/helpers/seller_helper.rb
module SellerHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@admin_user) do |f| %>
  <% if @admin_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_user.errors.count, "error") %> prohibited this admin_user from being saved:</h2>

      <ul>
      <% @admin_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field form-group">
      <%= f.label :用户名 %>
      <%= f.text_field :username ,class:"form-control"%>
    </div>
    <div class="field form-group">
      <%= f.label :密码 %>
      <%= f.password_field :password,class:"form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :确认密码%>
      <%= f.password_field :password_confirmation,class:"form-control" %>
    </div>
    <div class="actions form-group">
      <%= f.submit "确认" ,class:"btn btn-block btn-info"%>
    </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="container" style="margin-bottom:10px;width:50%">
	<h1>Editing Admin User</h1>

	<%= render 'form' %>

	<%= link_to '浏览', @admin_user ,class:'btn btn-inline btn-success'%> 
	<%= link_to '返回', admin_users_path,class:'btn btn-inline btn-warning' %>
</div>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>用户管理</h1>

<table class="table">
  <thead>
    <tr>
      <th>用户名</th>
      <th>身份</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_users.each do |admin_user| %>
      <tr>
        <td><%= admin_user.username %></td>
        <td><%= admin_user.discribe %></td>
        <td><%= link_to '详细信息', admin_user %></td>
        <td><%= link_to '编辑', edit_admin_user_path(admin_user) %></td>
        <td><%= link_to '删除', admin_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<div class="container">
<h1>注册</h1>

<%= render 'form' %>

<%= link_to '返回登录', admin_users_path,class:"btn btn-block btn-info" %>
</div>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>用户名:</strong>
  <%= @admin_user.username %>
</p>

<p>
  <strong>身份:</strong>
  <%= @admin_user.discribe %>
</p>

<%= link_to '编辑', edit_admin_user_path(@admin_user) %> |
<%= link_to '返回', admin_users_path %>